CREATE TABLE IF NOT EXISTS traverse (
    id UUID PRIMARY KEY,
    time_zone VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    adjustment_version VARCHAR(50) NOT NULL,
    total_length_m DOUBLE PRECISION NOT NULL,
    closure_dx_m DOUBLE PRECISION NOT NULL,
    closure_dy_m DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS traverse_leg (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    traverse_id UUID NOT NULL REFERENCES traverse(id),
    sequence_no INTEGER NOT NULL,
    from_station_no VARCHAR(100) NOT NULL,
    to_station_no VARCHAR(100) NOT NULL,
    observed_distance_m DOUBLE PRECISION NOT NULL,
    observed_azimuth_deg DOUBLE PRECISION NOT NULL,
    raw_dx_m DOUBLE PRECISION NOT NULL,
    raw_dy_m DOUBLE PRECISION NOT NULL,
    correction_dx_m DOUBLE PRECISION NOT NULL,
    correction_dy_m DOUBLE PRECISION NOT NULL,
    adjusted_dx_m DOUBLE PRECISION NOT NULL,
    adjusted_dy_m DOUBLE PRECISION NOT NULL,
    adjusted_end_x_m DOUBLE PRECISION NOT NULL,
    adjusted_end_y_m DOUBLE PRECISION NOT NULL,
    CONSTRAINT traverse_leg_sequence_unique UNIQUE (traverse_id, sequence_no)
);
